### ISSUE TITLE
Undefined  class "dagnn.GausianNoise"

### ISSUE THREAD

**Issue by lyzhangjm** [layumi/2016_GAN_Matlab#3]
Hello, when I run the train_gan_3, there is a error:
>> train_gan_3
11  net = GDnet_3();
Undefined variable "dagnn" or class "dagnn.GausianNoise".

**Comment by layumi** [comment]
@lyzhangjm 
It seems to  be that you do not include the dagnn.
Have you used the `gpu_compile.m` to compile the matconvnet?
In the `gpu_compile.m`, there is a command `addpath matlab`, which add the path `matlab/+dagnn`
